STRINGS: dict[str, dict] = {
    "en": {
        "window_title": "Warehouse Master",
        "tab_labels": "Labels",
        "tab_reassembly": "Reassembly",
        "menu_settings": "Settings",
        "menu_preferences": "Preferences...",
        # labels tab
        "grp_label_type": "1. Label Type",
        "grp_label_settings": "2. Label Settings",
        "grp_ranges": "3. Number Ranges",
        "rb_single": "Single label (58×40 mm)",
        "rb_2x2": "Grid 2×2 (58×40 mm)",
        "rb_4x4": "Grid 4×4 (120×75 mm)",
        "lbl_font_size": "Font size:",
        "ph_label_name": "Label name",
        "chk_autoprint": "Auto-print",
        "lbl_printer": "Printer:",
        "chk_temp": "Temporary mode (delete on exit)",
        "btn_generate": "Generate PDF",
        "btn_print": "Print",
        "btn_generating": "Generating...",
        "lbl_total": "Total: {n}",
        # reassembly tab
        "grp_order_info": "Order Info",
        "grp_parts": "Parts",
        "grp_result": "Result",
        "lbl_order": "Order:",
        "order_types": ["WO", "RO"],
        "ph_order_num": "Number",
        "lbl_laptop_id": "Laptop ID:",
        "ph_laptop_id": "Laptop ID",
        "lbl_parts_field": "Parts (ID):",
        "ph_parts": "e.g. 12, 64, 105",
        "lbl_ssd_field": "SSD (ID):",
        "ph_ssd": "SSD ID",
        "lbl_akb_field": "Battery (ID):",
        "ph_akb": "Battery ID",
        "btn_apply": "Apply changes",
        "btn_applying": "Working...",
        "lbl_comment": "Comment:",
        "lbl_tech": "Tech operation:",
        # preferences dialog
        "dlg_title": "Settings",
        "dlg_theme": "Theme:",
        "theme_dark": "Dark",
        "theme_light": "Light",
        "dlg_language": "Language:",
        "dlg_sheet_url": "Google Sheet URL:",
        "dlg_save_folder": "Save folder:",
        "dlg_select_folder": "Select folder",
        "btn_save": "Save",
        "btn_cancel": "Cancel",
        # messages
        "err_title": "Error",
        "err_no_ranges": "Enter at least one range",
        "err_start_gt_end": "Start > end in range: {a}–{b}",
        "err_no_sheet_url": "Set the Google Sheet URL in Settings",
        "err_no_order": "Fill in order number and laptop ID",
        "err_no_parts": "Add at least one part",
        "msg_done_title": "Done",
        "msg_done": "Spreadsheet updated successfully",
    },
    "ru": {
        "window_title": "Warehouse Master",
        "tab_labels": "Этикетки",
        "tab_reassembly": "Пересборка",
        "menu_settings": "Настройки",
        "menu_preferences": "Настройки...",
        "grp_label_type": "1. Тип этикетки",
        "grp_label_settings": "2. Параметры",
        "grp_ranges": "3. Диапазоны номеров",
        "rb_single": "Одиночная (58×40 мм)",
        "rb_2x2": "Сетка 2×2 (58×40 мм)",
        "rb_4x4": "Сетка 4×4 (120×75 мм)",
        "lbl_font_size": "Размер шрифта:",
        "ph_label_name": "Название этикетки",
        "chk_autoprint": "Автопечать",
        "lbl_printer": "Принтер:",
        "chk_temp": "Временный режим (удалить при выходе)",
        "btn_generate": "Создать PDF",
        "btn_print": "Печать",
        "btn_generating": "Генерация...",
        "lbl_total": "Итого: {n}",
        "grp_order_info": "Заказ",
        "grp_parts": "Запчасти",
        "grp_result": "Результат",
        "lbl_order": "Заказ:",
        "order_types": ["ЗП", "ВЗ"],
        "ph_order_num": "Номер",
        "lbl_laptop_id": "ID ноута:",
        "ph_laptop_id": "ID Ноутбука",
        "lbl_parts_field": "Запчасти (ID):",
        "ph_parts": "Например: 12, 64, 105",
        "lbl_ssd_field": "SSD (ID):",
        "ph_ssd": "ID SSD",
        "lbl_akb_field": "АКБ (ID):",
        "ph_akb": "ID АКБ",
        "btn_apply": "Внести изменения",
        "btn_applying": "Обработка...",
        "lbl_comment": "Комментарий:",
        "lbl_tech": "Техоперация:",
        "dlg_title": "Настройки",
        "dlg_theme": "Тема:",
        "theme_dark": "Тёмная",
        "theme_light": "Светлая",
        "dlg_language": "Язык:",
        "dlg_sheet_url": "URL таблицы Google:",
        "dlg_save_folder": "Папка сохранения:",
        "dlg_select_folder": "Выбрать папку",
        "btn_save": "Сохранить",
        "btn_cancel": "Отмена",
        "err_title": "Ошибка",
        "err_no_ranges": "Введите хотя бы один диапазон",
        "err_start_gt_end": "Начало > конец в диапазоне: {a}–{b}",
        "err_no_sheet_url": "Укажите URL таблицы в настройках",
        "err_no_order": "Заполните номер заказа и ID ноутбука",
        "err_no_parts": "Добавьте хотя бы одну запчасть",
        "msg_done_title": "Готово",
        "msg_done": "Таблицы успешно обновлены",
    },
}
